### ISSUE TITLE
Feature: Add `script.onerror` handler.

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/little-loader#15]
* [x] Add `onerror` handler
* [x] Test errors down to IE8 (may be future work).
* [x] Figure out IE8 `script.onerror` story.
* [x] Update doc byte sizes.
* [x] Update doc usage stuff.

New API:

```js
window._lload("http://example.com/foo.js", function (err) {
  if (err) { console.log("OH NOES", err); }
  // foo.js is loaded!
}/*, [optional context variable here] */);
```

/cc @PeoB

**Comment by exogen** [comment]
Just adding a note here that for old-IE we'll need a disclaimer, because `onerror` unfortunately just doesn't work. (Although, who knows, maybe everyone else just got that wrong too and we can find a way :wink:).

Having a `timeout` option could come in handy, especially in that old-IE case where it could be the stand-in for `onerror`. The problem with having a timeout is that you can't guarantee that the script won't still load after your timeout fires, so the code could still be executed after you'd handled the timeout...

**Comment by ryan-roemer** [comment]
UPDATE: Error capture works so far for all but IE8 for a 404'ing script.

* **FAIL**: IE_8_Windows_2008_Desktop
* **PASS**: IE_9_Windows_2008_Desktop
* **PASS**: IE_10_Windows_2012_Desktop
* **PASS**: IE_11_Windows_2012_R2_Desktop
