### ISSUE TITLE
TEST SCENARIO: Load same script twice.

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/little-loader#4]

**Comment by exogen** [comment]
Should be handled in #24's jQuery test, which loads jQuery from the same URL more than once.

For anyone reading this in the future, this tests a couple things:

1. That we handle IE8 & IE9's load-from-cache `onreadystatechange` sequence correctly
2. That we'll actually load the script twice, instead of remembering that it was already run like some other loaders

**Comment by ryan-roemer** [comment]
Yep -- I added this ticket before implementing the `jquery` tests.

Minor side note for at least RequireJS -- RJS is _supposed_ to not reload existing cached modules (and you can wipe the cache explicitly).

Closing!
