### ISSUE TITLE
Feature: UMD Wrapper + Tests

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/little-loader#9]
Tasks

* [x] Add UMD wrapper
* [x] Likely want to keep `window._lload` in all scenarios for joint "inline + built" bootstrap scenario.
* [ ] TEST: webpack-built frontend
* [ ] TEST: RequireJS frontend

**Comment by ryan-roemer** [comment]
NOTE: Presently **not** planning on doing this. Instead, we're adding docs for RequireJS and Webpack.

**Comment by exogen** [comment]
I've been thinking about this and took a look at #13. I agree on doing without the UMD build.

In my opinion, the source file `little-loader.js` should not attach to `window` and just attach to `module.exports`. Instead of forcing the global `window` variable, assume the default will be for people to install via npm and include it in their app's bundle via webpack or Browserify. Then the load function isolated/contained just like any other npm module that gets bundled.

Then for our `dist` file, we *do* expose it on `window` by using webpack's `expose-loader`. If you want to use little-loader as a drop-in `<script>` tag, use the dist file and it'll be on `window._lload`. If you just `require` it like a normal module and then it gets bundled with webpack, then it's contained (or you can choose to expose it however you like).

(I'm not sure about RequireJS, but we could just say it should point to the `dist` file and use the same `shim` you document in #13.)

**Comment by ryan-roemer** [comment]
@exogen -- The boilerplate for webpack is going to be a significant bundle increase that is not our primary use case. The `window` can be _removed_ via webpack magic, so this is the tightest solution...

**Comment by ryan-roemer** [comment]
Also, `module.exports` in the source won't work for RequireJS (AFAICT) and if you're _building_ it into RequireJS source, you're going to want the unminified raw source.

**Comment by exogen** [comment]
I don't really agree that the primary use case is being 500-something bytes instead of 700-something bytes (which is what I got with webpack – there's not a ton of overhead for such a simple module). All other loaders are way bigger than that anyway.

I don't understand the wanting-unminified-source-with-RequireJS thing, can you explain?

**Comment by ryan-roemer** [comment]
@exogen -- Our primary use case is inlining on every page. Everything else is "nice to have". I'm not adding a huge boilerplate and a third party loader for a single file that just needs uglify :wink:

**Comment by ryan-roemer** [comment]
Or, out another way -- I can handcraft a manual UMD wrapper for a single file that is way smaller than webpack's boilerplate. So webpack for a single file is really out for our build here (although we can support it and RJS for our consumers).

**Comment by ryan-roemer** [comment]
For example, a completely functional full UMD wrapper adds `141` bytes (`666 - 525` (our current bundle size)).

```diff
diff --git a/lib/little-loader.js b/lib/little-loader.js
index cbd5195..2cc43aa 100644
--- a/lib/little-loader.js
+++ b/lib/little-loader.js
@@ -55,7 +55,7 @@
    * @param {Object}    context   (Optional) Callback context
    * @returns {void}
    */
-  window._lload = function (src, callback, context) {
+  var _lload = function (src, callback, context) {
     /*eslint max-statements: [2, 20]*/
     context = context || this;
     var script = doc.createElement("script");
@@ -135,4 +135,22 @@
       _addScript(script);
     }
   };
+
+  // UMD wrapper.
+  if (typeof exports === "object" && typeof module === "object") {
+    // NodeJS
+    module.exports = _lload;
+
+  } else if (typeof define === "function" && define.amd) {
+    // AMD: Assumes importing `chai` and `jquery`. Returns a function to
+    //      inject with `chai.use()`.
+    //
+    // See: https://github.com/chaijs/chai-jquery/issues/27
+    define([], function () { return _lload; });
+
+  } else {
+    // Other environment (usually <script> tag): plug in to global chai
+    // instance directly.
+    window._lload = _lload;
+  }
 }());
```

**Comment by exogen** [comment]
OK! Not using webpack for that is totally fine – I'm trying to get to a certain result, not use a particular tool.

I still don't really like the UMD build, but if we could achieve this that way, I suppose it's okay. (The reason I don't like UMD is because it adds uncertainty to what will happen – if some other script on the page happens to add `define` or `module` or `exports` then all bets are off).

The result I want is:
* `dist` bundle: attaches to `window._lload`, always, no matter what.
* source file: just exports like normal, then people (outside of this org and our exact use case) can choose to expose or isolate however they want. (preferably *without* needing special webpack loaders, with to me signal "this module was not written to play well with others")

**Comment by ryan-roemer** [comment]
@exogen -- For UMD wrappers, they're pretty much "how it's done" / "completely standard" at this point. So, so many libraries use them. We use a ton of libraries everywhere with UMD wrappers. And dev's should already know and it is reasonable to expect that if you manually play with `define`, etc. you are loading your footgun.

We have a specific use case to support RequireJS and inline, so we're not just a "only CommonJS" shop, so there's no reason to have a "`module.exports` over all!" mentality.

I've got a comparison PR of just the UMD enhancements to the compression PR at: https://github.com/walmartlabs/little-loader/pull/14/files

At this point do you feel more comfortable (given our use cases) with (1) `window._lload` always or (2) the handwritten UMD wrapper?

**Comment by exogen** [comment]
I think `window._lload`-always is bad from a "modern JS module that plays nice" standpoint. More comfortable with the UMD option, and I'll put my "assume an insanely hostile environment" fears aside. :wink:

I wonder if in the future, for people concerned about this type of thing (bytes and possibly-someone-else's `define` on the page) we could just offer multiple `dist` bundles (UMD, and a leaner one that always attaches to `window._lload`). Think I've seen a project or two offer that kind of choice before.

**Comment by ryan-roemer** [comment]
@exogen -- Cool.

For the multiple builds, I've definitely seen that for larger projects using a builder like Webpack spitting out different builds where the boilerplate overhead doesn't matter. I'm pretty sure that we could come up with something with our handcrafted boilerplate for CommonJS, AMD that programatically works.
